// Map from node id to live demo URL. Only nodes with an entry here show the popup.
export const DEMOS = {
  "gui-first-principles": "https://galmungral.github.io/gui-first-principles/",
  michelangelo:           "https://galmungral.github.io/michelangelo/",
  "vector-rendering":     "https://galmungral.github.io/vector-rendering/",
  "newton-vg":            "https://galmungral.github.io/newton-vg/",
  "gl-raytracer":         "https://galmungral.github.io/gl-raytracer/",
  "3d-rasterizer":        "https://galmungral.github.io/3d-rasterizer/",
  "gl-fdm-2d":            "https://galmungral.github.io/gl-fdm-2d/",
  "gl-fdm-3d":            "https://galmungral.github.io/gl-fdm-3d/",
  "wasm-particle-sim":    "https://galmungral.github.io/wasm-particle-sim/",
  "wasm-fvm-cfd":         "https://galmungral.github.io/wasm-fvm-cfd/",
  hillshade:              "https://galmungral.github.io/hillshade/",
  "terrain-faulting":     "https://galmungral.github.io/terrain-faulting/",
  "oblique-mercator":     "https://galmungral.github.io/oblique-mercator/",
  "raster-tile-renderer": "https://galmungral.github.io/raster-tile-renderer/",
  "vector-tiles-gl":      "https://galmungral.github.io/vector-tiles-gl/",
  "visible-human-vtk":    "https://galmungral.github.io/visible-human-vtk/",
  "visible-human-slicer": "https://galmungral.github.io/visible-human-slicer/",
  "visible-human-volume": "https://galmungral.github.io/visible-human-volume/",
  "shape-from-shading":   "https://galmungral.github.io/shape-from-shading/",
  "gl-gaussian-splat":    "https://galmungral.github.io/gl-gaussian-splat/",
  "image-generation-notebooks": "https://galmungral.github.io/image-generation-notebooks/",
  "mol-renderer":         "https://galmungral.github.io/mol-renderer/",
  "conformer-viewer":     "https://galmungral.github.io/conformer-viewer/",
  "spectral-color":       "https://galmungral.github.io/spectral-color/",
  "qft-viz":              "https://galmungral.github.io/qft-viz/",
  "kanbun-lang":          "https://galmungral.github.io/kanbun-lang/",
  "tidal-sphere":         "https://galmungral.github.io/tidal-sphere/",
  macrobook:              "https://galmungral.github.io/macrobook/",
};


export const TAGS = [
  "Geospatial",
  "2D Graphics",
  "UI",
  "Simulation",
  "GPU",
  "3D Graphics",
  "Chemical",
  "Medical",
  "Visualization",
  "Computer Vision",
  "Statistical & ML",
  "Networking",
  "CS Foundations",
];

export const NODES = [
  { id: "replay",                   tags: ["UI", "2D Graphics"] },
  { id: "gui-first-principles",     tags: ["UI", "2D Graphics"] },
  { id: "michelangelo",             tags: ["UI", "2D Graphics"] },
  { id: "vector-rendering",         tags: ["2D Graphics"] },
  { id: "svg.c",                    tags: ["2D Graphics"] },
  { id: "newton-vg",                tags: ["2D Graphics", "GPU"] },
  { id: "cpu-raytracer",            tags: ["3D Graphics"] },
  { id: "gl-raytracer",             tags: ["3D Graphics", "GPU"] },
  { id: "3d-rasterizer",            tags: ["3D Graphics"] },
  { id: "gl-gaussian-splat",        tags: ["3D Graphics", "GPU"] },
  { id: "gl-fdm-2d",                tags: ["Simulation", "GPU", "Visualization"] },
  { id: "gl-fdm-3d",                tags: ["Simulation", "3D Graphics", "GPU", "Visualization"] },
  { id: "wasm-particle-sim",        tags: ["Simulation", "Visualization"] },
  { id: "wasm-fvm-cfd",             tags: ["Simulation", "GPU", "Visualization"] },
  { id: "hillshade",                tags: ["Geospatial", "3D Graphics", "GPU", "Visualization"] },
  { id: "shortcut-to-graphics",     tags: ["Geospatial", "3D Graphics", "Visualization"] },
  { id: "terrain-faulting",         tags: ["Simulation", "Visualization"] },
  { id: "oblique-mercator",         tags: ["Geospatial", "3D Graphics", "Visualization"] },
  { id: "raster-tile-renderer",     tags: ["Geospatial", "2D Graphics"] },
  { id: "vector-tiles-gl",          tags: ["Geospatial", "2D Graphics", "GPU"] },
  { id: "visible-human-explore",    tags: ["Medical", "Visualization"] },
  { id: "visible-human-vtk",        tags: ["Medical", "Visualization"] },
  { id: "visible-human-slicer",     tags: ["Medical", "3D Graphics", "Visualization"] },
  { id: "visible-human-volume",     tags: ["Medical", "3D Graphics", "GPU", "Visualization"] },
  { id: "scivis-primer",            tags: ["Simulation", "Visualization"] },
  { id: "shape-from-shading",       tags: ["3D Graphics", "Computer Vision", "Visualization"] },
  { id: "mol-renderer",             tags: ["Chemical", "3D Graphics", "Visualization"] },
  { id: "conformer-viewer",         tags: ["Chemical", "3D Graphics", "Visualization"] },
  { id: "spectral-color",           tags: ["3D Graphics", "Visualization"] },
  { id: "qft-viz",                  tags: ["Visualization"] },
  { id: "backprop",                 tags: ["Statistical & ML", "Visualization"] },
  { id: "gpu-patterns",             tags: ["GPU"] },
  { id: "tinyvm",                   tags: ["CS Foundations"] },
  { id: "tinyos",                   tags: ["CS Foundations"] },
  { id: "universal-turing-machine", tags: ["CS Foundations"] },
  { id: "kanbun-lang",              tags: ["UI"] },
  { id: "plato",                    tags: ["Statistical & ML"] },
  { id: "image-generation-notebooks", tags: ["Statistical & ML", "Computer Vision"] },
  { id: "tidal-sphere",             tags: ["Simulation", "3D Graphics"] },
  { id: "macrobook",                tags: ["CS Foundations"] },
  { id: "telescope",                tags: ["Networking"] },
  { id: "wormhole",                 tags: ["Networking"] },
];

export const CONNECTIONS = [
  // UI / 2D Graphics spine
  ["replay",               "gui-first-principles"],
  ["replay",               "michelangelo"],
  ["gui-first-principles", "michelangelo"],
  ["gui-first-principles", "vector-rendering"],
  ["gui-first-principles", "tinyos"],
  ["michelangelo",         "raster-tile-renderer"],
  ["michelangelo",         "kanbun-lang"],
  ["vector-rendering",     "svg.c"],
  ["vector-rendering",     "newton-vg"],
  ["vector-rendering",     "3d-rasterizer"],
  ["vector-rendering",     "vector-tiles-gl"],
  ["raster-tile-renderer", "vector-tiles-gl"],

  // 3D Rendering spine
  ["3d-rasterizer",        "cpu-raytracer"],
  ["cpu-raytracer",        "gl-raytracer"],
  ["3d-rasterizer",        "vector-tiles-gl"],
  ["3d-rasterizer",        "wasm-particle-sim"],
  ["3d-rasterizer",        "terrain-faulting"],
  ["3d-rasterizer",        "mol-renderer"],
  ["3d-rasterizer",        "conformer-viewer"],
  ["3d-rasterizer",        "tidal-sphere"],
  ["3d-rasterizer",        "scivis-primer"],

  // Gaussian splatting
  ["gl-raytracer",         "gl-gaussian-splat"],
  ["3d-rasterizer",        "gl-gaussian-splat"],
  ["gpu-patterns",         "gl-gaussian-splat"],

  // GPU / raytracer
  ["newton-vg",            "gl-raytracer"],
  ["newton-vg",            "gpu-patterns"],
  ["gl-raytracer",         "hillshade"],
  ["gl-raytracer",         "gl-fdm-3d"],
  ["gl-raytracer",         "oblique-mercator"],
  ["gl-raytracer",         "visible-human-volume"],

  // Simulation / FDM
  ["hillshade",            "gl-fdm-2d"],
  ["hillshade",            "gl-fdm-3d"],
  ["hillshade",            "shortcut-to-graphics"],
  ["hillshade",            "shape-from-shading"],
  ["gl-fdm-2d",            "gl-fdm-3d"],
  ["gl-fdm-2d",            "wasm-fvm-cfd"],
  ["gl-fdm-2d",            "gpu-patterns"],
  ["gl-fdm-3d",            "wasm-fvm-cfd"],
  ["gl-fdm-3d",            "gpu-patterns"],
  ["gl-fdm-3d",            "visible-human-volume"],
  ["wasm-particle-sim",    "wasm-fvm-cfd"],
  ["wasm-particle-sim",    "tidal-sphere"],
  ["wasm-particle-sim",    "shape-from-shading"],
  ["wasm-fvm-cfd",         "shape-from-shading"],
  ["wasm-fvm-cfd",         "scivis-primer"],

  // Geospatial
  ["oblique-mercator",     "raster-tile-renderer"],
  ["oblique-mercator",     "vector-tiles-gl"],

  // Medical
  ["visible-human-explore","visible-human-vtk"],
  ["visible-human-explore","scivis-primer"],
  ["visible-human-vtk",    "visible-human-slicer"],
  ["visible-human-vtk",    "visible-human-volume"],
  ["visible-human-vtk",    "scivis-primer"],
  // Chemical
  ["mol-renderer",         "conformer-viewer"],
  ["mol-renderer",         "tidal-sphere"],
  ["conformer-viewer",     "tidal-sphere"],

  // Spectral color
  ["spectral-color",       "3d-rasterizer"],
  ["spectral-color",       "cpu-raytracer"],
  ["spectral-color",       "gl-raytracer"],

  // Computer Vision / Math
  ["shape-from-shading",   "qft-viz"],

  // CS Foundations
  ["universal-turing-machine", "tinyvm"],
  ["tinyvm",               "tinyos"],
  ["tinyvm",               "macrobook"],
  ["tinyos",               "telescope"],

  // Networking
  ["telescope",            "wormhole"],
  ["plato",                "backprop"],
  ["plato",                "image-generation-notebooks"],
  ["backprop",             "image-generation-notebooks"],
  ["vector-rendering",     "image-generation-notebooks"],
  ["cpu-raytracer",        "image-generation-notebooks"],
  ["gl-gaussian-splat",    "image-generation-notebooks"],
  ["3d-rasterizer",        "image-generation-notebooks"],
];