export const TAGS = {
  "UI":               "#60a5fa",
  "2D Graphics":      "#38bdf8",
  "3D Rendering":     "#f97316",
  "GPU":              "#ef4444",
  "Simulation":       "#facc15",
  "Geospatial":       "#34d399",
  "Medical":          "#a78bfa",
  "Chemical":         "#f472b6",
  "Math":             "#fb923c",
  "Literate":         "#cbd5e1",
  "Computer Vision":  "#e879f9",
  "CS Foundations":   "#94a3b8",
  "Networking":       "#64748b",
  "Statistical & ML": "#a3a3a3",
};

export const NODES = [
  { id: "replay",                   tags: ["UI", "2D Graphics"] },
  { id: "gui-first-principles",     tags: ["UI", "2D Graphics", "Literate"] },
  { id: "michelangelo",             tags: ["UI", "2D Graphics"] },
  { id: "vector-rendering",         tags: ["2D Graphics"] },
  { id: "svg.c",                    tags: ["2D Graphics"] },
  { id: "newton-vg",                tags: ["2D Graphics", "GPU"] },
  { id: "cpu-raytracer",            tags: ["3D Rendering"] },
  { id: "gl-raytracer",             tags: ["3D Rendering", "GPU"] },
  { id: "3d-rasterizer",            tags: ["3D Rendering"] },
  { id: "gl-fdm-2d",                tags: ["Simulation", "GPU"] },
  { id: "gl-fdm-3d",                tags: ["Simulation", "3D Rendering", "GPU"] },
  { id: "wasm-particle-sim",        tags: ["Simulation"] },
  { id: "wasm-fvm-cfd",             tags: ["Simulation", "GPU"] },
  { id: "hillshade",                tags: ["Geospatial", "3D Rendering", "GPU"] },
  { id: "shortcut-to-graphics",     tags: ["Geospatial", "3D Rendering", "Literate"] },
  { id: "terrain-faulting",         tags: ["Geospatial", "Simulation"] },
  { id: "oblique-mercator",         tags: ["Geospatial", "3D Rendering"] },
  { id: "raster-tile-renderer",     tags: ["Geospatial", "2D Graphics"] },
  { id: "vector-tiles-gl",          tags: ["Geospatial", "2D Graphics", "GPU"] },
  { id: "visible-human-explore",    tags: ["Medical", "Literate"] },
  { id: "visible-human-vtk",        tags: ["Medical"] },
  { id: "visible-human-slicer",     tags: ["Medical"] },
  { id: "visible-human-volume",     tags: ["Medical", "3D Rendering", "GPU"] },
  { id: "scivis-primer",            tags: ["Simulation"] },
  { id: "shape-from-shading",       tags: ["Math", "3D Rendering", "Computer Vision"] },
  { id: "mol-renderer",             tags: ["Chemical"] },
  { id: "conformer-viewer",         tags: ["Chemical"] },
  { id: "spectral-color",           tags: ["Chemical", "Math"] },
  { id: "qft-viz",                  tags: ["Math"] },
  { id: "backprop",                 tags: ["Math", "Literate", "Statistical & ML"] },
  { id: "gpu-patterns",             tags: ["GPU"] },
  { id: "tinyvm",                   tags: ["CS Foundations"] },
  { id: "tinyos",                   tags: ["CS Foundations"] },
  { id: "universal-turing-machine", tags: ["CS Foundations"] },
  { id: "kanbun-lang",              tags: ["CS Foundations"] },
  { id: "plato",                    tags: ["Statistical & ML"] },
  { id: "tidal-sphere",             tags: ["Simulation", "3D Rendering"] },
  { id: "macrobook",                tags: ["CS Foundations"] },
  { id: "telescope",                tags: ["Networking"] },
  { id: "wormhole",                 tags: ["Networking"] },
];

// Edges grouped by the tag boundary they cross.
// A group key of "A" means edges within cluster A.
// A group key of "A — B" means edges between clusters A and B.
// The existence of a group implies those two tag clusters are related.
export const CONNECTIONS = {
  "UI": [
    ["replay", "gui-first-principles"],
    ["replay", "michelangelo"],
    ["gui-first-principles", "michelangelo"],
  ],
  "UI — 2D Graphics": [
    ["gui-first-principles", "vector-rendering"],
    ["gui-first-principles", "svg.c"],
    ["michelangelo", "vector-rendering"],
    ["michelangelo", "svg.c"],
    ["michelangelo", "newton-vg"],
  ],
  "2D Graphics": [
    ["vector-rendering", "svg.c"],
    ["vector-rendering", "newton-vg"],
    ["svg.c", "newton-vg"],
  ],
  "2D Graphics — 3D Rendering": [
    ["vector-rendering", "3d-rasterizer"],
    ["svg.c", "cpu-raytracer"],
    ["svg.c", "3d-rasterizer"],
    ["newton-vg", "3d-rasterizer"],
  ],
  "2D Graphics — Geospatial": [
    ["newton-vg", "vector-tiles-gl"],
  ],
  "3D Rendering": [
    ["cpu-raytracer", "gl-raytracer"],
    ["cpu-raytracer", "3d-rasterizer"],
  ],
  "3D Rendering — Simulation": [
    ["gl-raytracer", "gl-fdm-2d"],
    ["gl-raytracer", "gl-fdm-3d"],
    ["3d-rasterizer", "gl-fdm-2d"],
    ["3d-rasterizer", "wasm-particle-sim"],
    ["cpu-raytracer", "wasm-particle-sim"],
    ["3d-rasterizer", "tidal-sphere"],
  ],
  "3D Rendering — Geospatial": [
    ["gl-raytracer", "hillshade"],
    ["gl-raytracer", "shortcut-to-graphics"],
    ["gl-raytracer", "oblique-mercator"],
    ["gl-fdm-3d", "oblique-mercator"],
    ["3d-rasterizer", "terrain-faulting"],
    ["3d-rasterizer", "vector-tiles-gl"],
  ],
  "3D Rendering — Medical": [
    ["gl-raytracer", "visible-human-volume"],
    ["3d-rasterizer", "visible-human-slicer"],
  ],
  "3D Rendering — Chemical": [
    ["3d-rasterizer", "mol-renderer"],
  ],
  "GPU": [
    ["gl-raytracer", "gpu-patterns"],
    ["gl-fdm-3d", "gpu-patterns"],
    ["oblique-mercator", "gpu-patterns"],
  ],
  "Simulation": [
    ["gl-fdm-2d", "gl-fdm-3d"],
    ["gl-fdm-2d", "wasm-particle-sim"],
    ["gl-fdm-2d", "wasm-fvm-cfd"],
    ["gl-fdm-3d", "wasm-particle-sim"],
    ["gl-fdm-3d", "wasm-fvm-cfd"],
    ["wasm-particle-sim", "wasm-fvm-cfd"],
    ["gl-fdm-2d", "tidal-sphere"],
  ],
  "Simulation — Geospatial": [
    ["gl-fdm-2d", "terrain-faulting"],
    ["gl-fdm-3d", "hillshade"],
    ["gl-fdm-3d", "shortcut-to-graphics"],
    ["gl-fdm-3d", "terrain-faulting"],
    ["wasm-fvm-cfd", "hillshade"],
    ["wasm-fvm-cfd", "shortcut-to-graphics"],
    ["wasm-fvm-cfd", "terrain-faulting"],
    ["wasm-fvm-cfd", "raster-tile-renderer"],
    ["terrain-faulting", "tidal-sphere"],
  ],
  "Simulation — Medical": [
    ["gl-fdm-2d", "visible-human-vtk"],
    ["gl-fdm-3d", "visible-human-explore"],
    ["gl-fdm-3d", "conformer-viewer"],
    ["visible-human-explore", "scivis-primer"],
    ["visible-human-vtk", "scivis-primer"],
  ],
  "Simulation — Math": [
    ["wasm-fvm-cfd", "shape-from-shading"],
    ["wasm-fvm-cfd", "qft-viz"],
    ["wasm-fvm-cfd", "backprop"],
  ],
  "Simulation — Chemical": [
    ["wasm-fvm-cfd", "spectral-color"],
  ],
  "Geospatial": [
    ["hillshade", "shortcut-to-graphics"],
    ["hillshade", "oblique-mercator"],
    ["oblique-mercator", "raster-tile-renderer"],
    ["oblique-mercator", "vector-tiles-gl"],
  ],
  "Geospatial — Medical": [
    ["oblique-mercator", "visible-human-volume"],
    ["shortcut-to-graphics", "visible-human-explore"],
  ],
  "Geospatial — Math": [
    ["hillshade", "shape-from-shading"],
    ["shortcut-to-graphics", "shape-from-shading"],
    ["shortcut-to-graphics", "qft-viz"],
    ["shortcut-to-graphics", "backprop"],
  ],
  "Geospatial — Chemical": [
    ["shortcut-to-graphics", "spectral-color"],
  ],
  "Medical": [
    ["visible-human-explore", "visible-human-vtk"],
    ["visible-human-vtk", "visible-human-slicer"],
    ["visible-human-vtk", "visible-human-volume"],
    ["visible-human-explore", "scivis-primer"],
    ["visible-human-vtk", "scivis-primer"],
  ],
  "Medical — Math": [
    ["visible-human-explore", "backprop"],
  ],
  "Chemical": [
    ["mol-renderer", "conformer-viewer"],
  ],
  "Math": [
    ["shape-from-shading", "qft-viz"],
    ["shape-from-shading", "backprop"],
    ["qft-viz", "backprop"],
  ],
  "Statistical & ML": [
    ["plato", "backprop"],
  ],
  "CS Foundations": [
    ["tinyvm", "tinyos"],
    ["tinyvm", "kanbun-lang"],
    ["tinyvm", "macrobook"],
    ["tinyos", "universal-turing-machine"],
    ["universal-turing-machine", "kanbun-lang"],
    ["universal-turing-machine", "macrobook"],
  ],
  "CS Foundations — Networking": [
    ["tinyos", "telescope"],
  ],
  "CS Foundations — UI": [
    ["replay", "kanbun-lang"],
    ["gui-first-principles", "tinyos"],
    ["gui-first-principles", "kanbun-lang"],
  ],
  "UI — Networking": [
    ["gui-first-principles", "telescope"],
    ["michelangelo", "telescope"],
  ],
  "UI — Geospatial": [
    ["michelangelo", "raster-tile-renderer"],
  ],
  "Networking": [
    ["telescope", "wormhole"],
  ],
};