// Map from node id to live demo URL. Only nodes with an entry here show the popup.
export const DEMOS = {
  "gui-first-principles": "https://galmungral.github.io/gui-first-principles/",
  "michelangelo":         "https://galmungral.github.io/michelangelo/",
  "vector-rendering":     "https://galmungral.github.io/vector-rendering/",
  "newton-vg":            "https://galmungral.github.io/newton-vg/",
  "gl-raytracer":         "https://galmungral.github.io/gl-raytracer/",
  "3d-rasterizer":        "https://galmungral.github.io/3d-rasterizer/",
  "gl-fdm-2d":            "https://galmungral.github.io/gl-fdm-2d/",
  "gl-fdm-3d":            "https://galmungral.github.io/gl-fdm-3d/",
  "wasm-particle-sim":    "https://galmungral.github.io/wasm-particle-sim/",
  "wasm-fvm-cfd":         "https://galmungral.github.io/wasm-fvm-cfd/",
  "hillshade":            "https://galmungral.github.io/hillshade/",
  "terrain-faulting":     "https://galmungral.github.io/terrain-faulting/",
  "oblique-mercator":     "https://galmungral.github.io/oblique-mercator/",
  "raster-tile-renderer": "https://galmungral.github.io/raster-tile-renderer/",
  "vector-tiles-gl":      "https://galmungral.github.io/vector-tiles-gl/",
  "visible-human-vtk":    "https://galmungral.github.io/visible-human-vtk/",
  "visible-human-slicer": "https://galmungral.github.io/visible-human-slicer/",
  "visible-human-volume": "https://galmungral.github.io/visible-human-volume/",
  "shape-from-shading":   "https://galmungral.github.io/shape-from-shading/",
  "mol-renderer":         "https://galmungral.github.io/mol-renderer/",
  "conformer-viewer":     "https://galmungral.github.io/conformer-viewer/",
  "spectral-color":       "https://galmungral.github.io/spectral-color/",
  "qft-viz":              "https://galmungral.github.io/qft-viz/",
  "kanbun-lang":          "https://galmungral.github.io/kanbun-lang/",
  "tidal-sphere":         "https://galmungral.github.io/tidal-sphere/",
  "macrobook":            "https://galmungral.github.io/macrobook/",
};

export const TAGS = [
  "UI",
  "2D Graphics",
  "3D Rendering",
  "GPU",
  "Simulation",
  "Geospatial",
  "Medical",
  "Chemical",
  "Math",
  "Computer Vision",
  "Statistical & ML",
  "CS Foundations",
  "Networking",
];

export const NODES = [
  { id: "replay",                   tags: ["UI", "2D Graphics"] },
  { id: "gui-first-principles",     tags: ["UI", "2D Graphics"] },
  { id: "michelangelo",             tags: ["UI", "2D Graphics"] },
  { id: "vector-rendering",         tags: ["2D Graphics"] },
  { id: "svg.c",                    tags: ["2D Graphics"] },
  { id: "newton-vg",                tags: ["2D Graphics", "GPU"] },
  { id: "cpu-raytracer",            tags: ["3D Rendering"] },
  { id: "gl-raytracer",             tags: ["3D Rendering", "GPU"] },
  { id: "3d-rasterizer",            tags: ["3D Rendering"] },
  { id: "gl-fdm-2d",                tags: ["Simulation", "GPU"] },
  { id: "gl-fdm-3d",                tags: ["Simulation", "3D Rendering", "GPU"] },
  { id: "wasm-particle-sim",        tags: ["Simulation"] },
  { id: "wasm-fvm-cfd",             tags: ["Simulation", "GPU"] },
  { id: "hillshade",                tags: ["Geospatial", "3D Rendering", "GPU"] },
  { id: "shortcut-to-graphics",     tags: ["Geospatial", "3D Rendering"] },
  { id: "terrain-faulting",         tags: ["Geospatial", "Simulation"] },
  { id: "oblique-mercator",         tags: ["Geospatial", "3D Rendering"] },
  { id: "raster-tile-renderer",     tags: ["Geospatial", "2D Graphics"] },
  { id: "vector-tiles-gl",          tags: ["Geospatial", "2D Graphics", "GPU"] },
  { id: "visible-human-explore",    tags: ["Medical"] },
  { id: "visible-human-vtk",        tags: ["Medical"] },
  { id: "visible-human-slicer",     tags: ["Medical"] },
  { id: "visible-human-volume",     tags: ["Medical", "3D Rendering", "GPU"] },
  { id: "scivis-primer",            tags: ["Simulation"] },
  { id: "shape-from-shading",       tags: ["Math", "3D Rendering", "Computer Vision"] },
  { id: "mol-renderer",             tags: ["Chemical"] },
  { id: "conformer-viewer",         tags: ["Chemical"] },
  { id: "spectral-color",           tags: ["Chemical", "Math"] },
  { id: "qft-viz",                  tags: ["Math"] },
  { id: "backprop",                 tags: ["Math", "Statistical & ML"] },
  { id: "gpu-patterns",             tags: ["GPU"] },
  { id: "tinyvm",                   tags: ["CS Foundations"] },
  { id: "tinyos",                   tags: ["CS Foundations"] },
  { id: "universal-turing-machine", tags: ["CS Foundations"] },
  { id: "kanbun-lang",              tags: ["CS Foundations"] },
  { id: "plato",                    tags: ["Statistical & ML"] },
  { id: "tidal-sphere",             tags: ["Simulation", "3D Rendering"] },
  { id: "macrobook",                tags: ["CS Foundations"] },
  { id: "telescope",                tags: ["Networking"] },
  { id: "wormhole",                 tags: ["Networking"] },
];

// All pairs [source, target, rating]. rating=0 means no link; 1–5 means linked (5=strongest).
export const CONNECTIONS = [
  // replay
  ["replay", "gui-first-principles",     3],
  ["replay", "michelangelo",             3],
  ["replay", "vector-rendering",         0],
  ["replay", "svg.c",                    0],
  ["replay", "newton-vg",                0],
  ["replay", "cpu-raytracer",            0],
  ["replay", "gl-raytracer",             0],
  ["replay", "3d-rasterizer",            0],
  ["replay", "gl-fdm-2d",                0],
  ["replay", "gl-fdm-3d",                0],
  ["replay", "wasm-particle-sim",        0],
  ["replay", "wasm-fvm-cfd",             0],
  ["replay", "hillshade",                0],
  ["replay", "shortcut-to-graphics",     0],
  ["replay", "terrain-faulting",         0],
  ["replay", "oblique-mercator",         0],
  ["replay", "raster-tile-renderer",     0],
  ["replay", "vector-tiles-gl",          0],
  ["replay", "visible-human-explore",    0],
  ["replay", "visible-human-vtk",        0],
  ["replay", "visible-human-slicer",     0],
  ["replay", "visible-human-volume",     0],
  ["replay", "scivis-primer",            0],
  ["replay", "shape-from-shading",       0],
  ["replay", "mol-renderer",             0],
  ["replay", "conformer-viewer",         0],
  ["replay", "spectral-color",           0],
  ["replay", "qft-viz",                  0],
  ["replay", "backprop",                 0],
  ["replay", "gpu-patterns",             0],
  ["replay", "tinyvm",                   0],
  ["replay", "tinyos",                   0],
  ["replay", "universal-turing-machine", 0],
  ["replay", "kanbun-lang",              0],
  ["replay", "plato",                    0],
  ["replay", "tidal-sphere",             0],
  ["replay", "macrobook",                0],
  ["replay", "telescope",                0],
  ["replay", "wormhole",                 0],

  // gui-first-principles
  ["gui-first-principles", "michelangelo",             5],
  ["gui-first-principles", "vector-rendering",         5],
  ["gui-first-principles", "svg.c",                    5],
  ["gui-first-principles", "newton-vg",                4],
  ["gui-first-principles", "cpu-raytracer",            0],
  ["gui-first-principles", "gl-raytracer",             0],
  ["gui-first-principles", "3d-rasterizer",            0],
  ["gui-first-principles", "gl-fdm-2d",                0],
  ["gui-first-principles", "gl-fdm-3d",                0],
  ["gui-first-principles", "wasm-particle-sim",        0],
  ["gui-first-principles", "wasm-fvm-cfd",             0],
  ["gui-first-principles", "hillshade",                0],
  ["gui-first-principles", "shortcut-to-graphics",     0],
  ["gui-first-principles", "terrain-faulting",         0],
  ["gui-first-principles", "oblique-mercator",         0],
  ["gui-first-principles", "raster-tile-renderer",     0],
  ["gui-first-principles", "vector-tiles-gl",          0],
  ["gui-first-principles", "visible-human-explore",    0],
  ["gui-first-principles", "visible-human-vtk",        0],
  ["gui-first-principles", "visible-human-slicer",     0],
  ["gui-first-principles", "visible-human-volume",     0],
  ["gui-first-principles", "scivis-primer",            0],
  ["gui-first-principles", "shape-from-shading",       0],
  ["gui-first-principles", "mol-renderer",             0],
  ["gui-first-principles", "conformer-viewer",         0],
  ["gui-first-principles", "spectral-color",           0],
  ["gui-first-principles", "qft-viz",                  0],
  ["gui-first-principles", "backprop",                 0],
  ["gui-first-principles", "gpu-patterns",             0],
  ["gui-first-principles", "tinyvm",                   0],
  ["gui-first-principles", "tinyos",                   3],
  ["gui-first-principles", "universal-turing-machine", 0],
  ["gui-first-principles", "kanbun-lang",              0],
  ["gui-first-principles", "plato",                    0],
  ["gui-first-principles", "tidal-sphere",             0],
  ["gui-first-principles", "macrobook",                0],
  ["gui-first-principles", "telescope",                0],
  ["gui-first-principles", "wormhole",                 0],

  // michelangelo
  ["michelangelo", "vector-rendering",         3],
  ["michelangelo", "svg.c",                    3],
  ["michelangelo", "newton-vg",                3],
  ["michelangelo", "cpu-raytracer",            0],
  ["michelangelo", "gl-raytracer",             0],
  ["michelangelo", "3d-rasterizer",            0],
  ["michelangelo", "gl-fdm-2d",                0],
  ["michelangelo", "gl-fdm-3d",                0],
  ["michelangelo", "wasm-particle-sim",        0],
  ["michelangelo", "wasm-fvm-cfd",             0],
  ["michelangelo", "hillshade",                0],
  ["michelangelo", "shortcut-to-graphics",     0],
  ["michelangelo", "terrain-faulting",         0],
  ["michelangelo", "oblique-mercator",         0],
  ["michelangelo", "raster-tile-renderer",     2],
  ["michelangelo", "vector-tiles-gl",          0],
  ["michelangelo", "visible-human-explore",    0],
  ["michelangelo", "visible-human-vtk",        0],
  ["michelangelo", "visible-human-slicer",     0],
  ["michelangelo", "visible-human-volume",     0],
  ["michelangelo", "scivis-primer",            0],
  ["michelangelo", "shape-from-shading",       0],
  ["michelangelo", "mol-renderer",             0],
  ["michelangelo", "conformer-viewer",         0],
  ["michelangelo", "spectral-color",           0],
  ["michelangelo", "qft-viz",                  0],
  ["michelangelo", "backprop",                 0],
  ["michelangelo", "gpu-patterns",             0],
  ["michelangelo", "tinyvm",                   0],
  ["michelangelo", "tinyos",                   0],
  ["michelangelo", "universal-turing-machine", 0],
  ["michelangelo", "kanbun-lang",              0],
  ["michelangelo", "plato",                    0],
  ["michelangelo", "tidal-sphere",             0],
  ["michelangelo", "macrobook",                0],
  ["michelangelo", "telescope",                0],
  ["michelangelo", "wormhole",                 0],

  // vector-rendering
  ["vector-rendering", "svg.c",                    5],
  ["vector-rendering", "newton-vg",                5],
  ["vector-rendering", "cpu-raytracer",            0],
  ["vector-rendering", "gl-raytracer",             0],
  ["vector-rendering", "3d-rasterizer",            3],
  ["vector-rendering", "gl-fdm-2d",                0],
  ["vector-rendering", "gl-fdm-3d",                0],
  ["vector-rendering", "wasm-particle-sim",        0],
  ["vector-rendering", "wasm-fvm-cfd",             0],
  ["vector-rendering", "hillshade",                0],
  ["vector-rendering", "shortcut-to-graphics",     0],
  ["vector-rendering", "terrain-faulting",         0],
  ["vector-rendering", "oblique-mercator",         0],
  ["vector-rendering", "raster-tile-renderer",     0],
  ["vector-rendering", "vector-tiles-gl",          4],
  ["vector-rendering", "visible-human-explore",    0],
  ["vector-rendering", "visible-human-vtk",        0],
  ["vector-rendering", "visible-human-slicer",     0],
  ["vector-rendering", "visible-human-volume",     0],
  ["vector-rendering", "scivis-primer",            0],
  ["vector-rendering", "shape-from-shading",       0],
  ["vector-rendering", "mol-renderer",             0],
  ["vector-rendering", "conformer-viewer",         0],
  ["vector-rendering", "spectral-color",           0],
  ["vector-rendering", "qft-viz",                  0],
  ["vector-rendering", "backprop",                 0],
  ["vector-rendering", "gpu-patterns",             0],
  ["vector-rendering", "tinyvm",                   0],
  ["vector-rendering", "tinyos",                   0],
  ["vector-rendering", "universal-turing-machine", 0],
  ["vector-rendering", "kanbun-lang",              0],
  ["vector-rendering", "plato",                    0],
  ["vector-rendering", "tidal-sphere",             0],
  ["vector-rendering", "macrobook",                0],
  ["vector-rendering", "telescope",                0],
  ["vector-rendering", "wormhole",                 0],

  // svg.c
  ["svg.c", "newton-vg",                5],
  ["svg.c", "cpu-raytracer",            0],
  ["svg.c", "gl-raytracer",             0],
  ["svg.c", "3d-rasterizer",            3],
  ["svg.c", "gl-fdm-2d",                0],
  ["svg.c", "gl-fdm-3d",                0],
  ["svg.c", "wasm-particle-sim",        0],
  ["svg.c", "wasm-fvm-cfd",             0],
  ["svg.c", "hillshade",                0],
  ["svg.c", "shortcut-to-graphics",     0],
  ["svg.c", "terrain-faulting",         0],
  ["svg.c", "oblique-mercator",         0],
  ["svg.c", "raster-tile-renderer",     0],
  ["svg.c", "vector-tiles-gl",          0],
  ["svg.c", "visible-human-explore",    0],
  ["svg.c", "visible-human-vtk",        0],
  ["svg.c", "visible-human-slicer",     0],
  ["svg.c", "visible-human-volume",     0],
  ["svg.c", "scivis-primer",            0],
  ["svg.c", "shape-from-shading",       0],
  ["svg.c", "mol-renderer",             0],
  ["svg.c", "conformer-viewer",         0],
  ["svg.c", "spectral-color",           0],
  ["svg.c", "qft-viz",                  0],
  ["svg.c", "backprop",                 0],
  ["svg.c", "gpu-patterns",             0],
  ["svg.c", "tinyvm",                   0],
  ["svg.c", "tinyos",                   0],
  ["svg.c", "universal-turing-machine", 0],
  ["svg.c", "kanbun-lang",              0],
  ["svg.c", "plato",                    0],
  ["svg.c", "tidal-sphere",             0],
  ["svg.c", "macrobook",                0],
  ["svg.c", "telescope",                0],
  ["svg.c", "wormhole",                 0],

  // newton-vg
  ["newton-vg", "cpu-raytracer",            1],
  ["newton-vg", "gl-raytracer",             2],
  ["newton-vg", "3d-rasterizer",            0],
  ["newton-vg", "gl-fdm-2d",                0],
  ["newton-vg", "gl-fdm-3d",                0],
  ["newton-vg", "wasm-particle-sim",        0],
  ["newton-vg", "wasm-fvm-cfd",             0],
  ["newton-vg", "hillshade",                0],
  ["newton-vg", "shortcut-to-graphics",     0],
  ["newton-vg", "terrain-faulting",         0],
  ["newton-vg", "oblique-mercator",         0],
  ["newton-vg", "raster-tile-renderer",     0],
  ["newton-vg", "vector-tiles-gl",          0],
  ["newton-vg", "visible-human-explore",    0],
  ["newton-vg", "visible-human-vtk",        0],
  ["newton-vg", "visible-human-slicer",     0],
  ["newton-vg", "visible-human-volume",     0],
  ["newton-vg", "scivis-primer",            0],
  ["newton-vg", "shape-from-shading",       0],
  ["newton-vg", "mol-renderer",             0],
  ["newton-vg", "conformer-viewer",         0],
  ["newton-vg", "spectral-color",           0],
  ["newton-vg", "qft-viz",                  0],
  ["newton-vg", "backprop",                 0],
  ["newton-vg", "gpu-patterns",             0],
  ["newton-vg", "tinyvm",                   0],
  ["newton-vg", "tinyos",                   0],
  ["newton-vg", "universal-turing-machine", 0],
  ["newton-vg", "kanbun-lang",              0],
  ["newton-vg", "plato",                    0],
  ["newton-vg", "tidal-sphere",             0],
  ["newton-vg", "macrobook",                0],
  ["newton-vg", "telescope",                0],
  ["newton-vg", "wormhole",                 0],

  // cpu-raytracer
  ["cpu-raytracer", "gl-raytracer",             5],
  ["cpu-raytracer", "3d-rasterizer",            4],
  ["cpu-raytracer", "gl-fdm-2d",                0],
  ["cpu-raytracer", "gl-fdm-3d",                0],
  ["cpu-raytracer", "wasm-particle-sim",        0],
  ["cpu-raytracer", "wasm-fvm-cfd",             0],
  ["cpu-raytracer", "hillshade",                0],
  ["cpu-raytracer", "shortcut-to-graphics",     0],
  ["cpu-raytracer", "terrain-faulting",         0],
  ["cpu-raytracer", "oblique-mercator",         0],
  ["cpu-raytracer", "raster-tile-renderer",     0],
  ["cpu-raytracer", "vector-tiles-gl",          0],
  ["cpu-raytracer", "visible-human-explore",    0],
  ["cpu-raytracer", "visible-human-vtk",        0],
  ["cpu-raytracer", "visible-human-slicer",     0],
  ["cpu-raytracer", "visible-human-volume",     0],
  ["cpu-raytracer", "scivis-primer",            0],
  ["cpu-raytracer", "shape-from-shading",       0],
  ["cpu-raytracer", "mol-renderer",             0],
  ["cpu-raytracer", "conformer-viewer",         0],
  ["cpu-raytracer", "spectral-color",           0],
  ["cpu-raytracer", "qft-viz",                  0],
  ["cpu-raytracer", "backprop",                 0],
  ["cpu-raytracer", "gpu-patterns",             0],
  ["cpu-raytracer", "tinyvm",                   0],
  ["cpu-raytracer", "tinyos",                   0],
  ["cpu-raytracer", "universal-turing-machine", 0],
  ["cpu-raytracer", "kanbun-lang",              0],
  ["cpu-raytracer", "plato",                    0],
  ["cpu-raytracer", "tidal-sphere",             0],
  ["cpu-raytracer", "macrobook",                0],
  ["cpu-raytracer", "telescope",                0],
  ["cpu-raytracer", "wormhole",                 0],

  // gl-raytracer
  ["gl-raytracer", "3d-rasterizer",            4],
  ["gl-raytracer", "gl-fdm-2d",                2],
  ["gl-raytracer", "gl-fdm-3d",                4],
  ["gl-raytracer", "wasm-particle-sim",        0],
  ["gl-raytracer", "wasm-fvm-cfd",             0],
  ["gl-raytracer", "hillshade",                2],
  ["gl-raytracer", "shortcut-to-graphics",     2],
  ["gl-raytracer", "terrain-faulting",         0],
  ["gl-raytracer", "oblique-mercator",         4],
  ["gl-raytracer", "raster-tile-renderer",     0],
  ["gl-raytracer", "vector-tiles-gl",          0],
  ["gl-raytracer", "visible-human-explore",    1],
  ["gl-raytracer", "visible-human-vtk",        1],
  ["gl-raytracer", "visible-human-slicer",     0],
  ["gl-raytracer", "visible-human-volume",     4],
  ["gl-raytracer", "scivis-primer",            1],
  ["gl-raytracer", "shape-from-shading",       0],
  ["gl-raytracer", "mol-renderer",             0],
  ["gl-raytracer", "conformer-viewer",         0],
  ["gl-raytracer", "spectral-color",           0],
  ["gl-raytracer", "qft-viz",                  0],
  ["gl-raytracer", "backprop",                 0],
  ["gl-raytracer", "gpu-patterns",             1],
  ["gl-raytracer", "tinyvm",                   0],
  ["gl-raytracer", "tinyos",                   0],
  ["gl-raytracer", "universal-turing-machine", 0],
  ["gl-raytracer", "kanbun-lang",              0],
  ["gl-raytracer", "plato",                    0],
  ["gl-raytracer", "tidal-sphere",             0],
  ["gl-raytracer", "macrobook",                0],
  ["gl-raytracer", "telescope",                0],
  ["gl-raytracer", "wormhole",                 0],

  // 3d-rasterizer
  ["3d-rasterizer", "gl-fdm-2d",                3],
  ["3d-rasterizer", "gl-fdm-3d",                0],
  ["3d-rasterizer", "wasm-particle-sim",        3],
  ["3d-rasterizer", "wasm-fvm-cfd",             0],
  ["3d-rasterizer", "hillshade",                0],
  ["3d-rasterizer", "shortcut-to-graphics",     0],
  ["3d-rasterizer", "terrain-faulting",         3],
  ["3d-rasterizer", "oblique-mercator",         0],
  ["3d-rasterizer", "raster-tile-renderer",     0],
  ["3d-rasterizer", "vector-tiles-gl",          3],
  ["3d-rasterizer", "visible-human-explore",    0],
  ["3d-rasterizer", "visible-human-vtk",        3],
  ["3d-rasterizer", "visible-human-slicer",     3],
  ["3d-rasterizer", "visible-human-volume",     0],
  ["3d-rasterizer", "scivis-primer",            3],
  ["3d-rasterizer", "shape-from-shading",       0],
  ["3d-rasterizer", "mol-renderer",             3],
  ["3d-rasterizer", "conformer-viewer",         3],
  ["3d-rasterizer", "spectral-color",           0],
  ["3d-rasterizer", "qft-viz",                  0],
  ["3d-rasterizer", "backprop",                 0],
  ["3d-rasterizer", "gpu-patterns",             0],
  ["3d-rasterizer", "tinyvm",                   0],
  ["3d-rasterizer", "tinyos",                   3],
  ["3d-rasterizer", "universal-turing-machine", 0],
  ["3d-rasterizer", "kanbun-lang",              0],
  ["3d-rasterizer", "plato",                    0],
  ["3d-rasterizer", "tidal-sphere",             3],
  ["3d-rasterizer", "macrobook",                0],
  ["3d-rasterizer", "telescope",                0],
  ["3d-rasterizer", "wormhole",                 0],

  // gl-fdm-2d
  ["gl-fdm-2d", "gl-fdm-3d",                5],
  ["gl-fdm-2d", "wasm-particle-sim",        0],
  ["gl-fdm-2d", "wasm-fvm-cfd",             4],
  ["gl-fdm-2d", "hillshade",                2],
  ["gl-fdm-2d", "shortcut-to-graphics",     2],
  ["gl-fdm-2d", "terrain-faulting",         1],
  ["gl-fdm-2d", "oblique-mercator",         0],
  ["gl-fdm-2d", "raster-tile-renderer",     0],
  ["gl-fdm-2d", "vector-tiles-gl",          0],
  ["gl-fdm-2d", "visible-human-explore",    0],
  ["gl-fdm-2d", "visible-human-vtk",        0],
  ["gl-fdm-2d", "visible-human-slicer",     0],
  ["gl-fdm-2d", "visible-human-volume",     0],
  ["gl-fdm-2d", "scivis-primer",            4],
  ["gl-fdm-2d", "shape-from-shading",       0],
  ["gl-fdm-2d", "mol-renderer",             0],
  ["gl-fdm-2d", "conformer-viewer",         0],
  ["gl-fdm-2d", "spectral-color",           0],
  ["gl-fdm-2d", "qft-viz",                  0],
  ["gl-fdm-2d", "backprop",                 0],
  ["gl-fdm-2d", "gpu-patterns",             4],
  ["gl-fdm-2d", "tinyvm",                   0],
  ["gl-fdm-2d", "tinyos",                   0],
  ["gl-fdm-2d", "universal-turing-machine", 0],
  ["gl-fdm-2d", "kanbun-lang",              0],
  ["gl-fdm-2d", "plato",                    0],
  ["gl-fdm-2d", "tidal-sphere",             0],
  ["gl-fdm-2d", "macrobook",                0],
  ["gl-fdm-2d", "telescope",                0],
  ["gl-fdm-2d", "wormhole",                 0],

  // gl-fdm-3d
  ["gl-fdm-3d", "wasm-particle-sim",        0],
  ["gl-fdm-3d", "wasm-fvm-cfd",             4],
  ["gl-fdm-3d", "hillshade",                2],
  ["gl-fdm-3d", "shortcut-to-graphics",     2],
  ["gl-fdm-3d", "terrain-faulting",         0],
  ["gl-fdm-3d", "oblique-mercator",         4],
  ["gl-fdm-3d", "raster-tile-renderer",     0],
  ["gl-fdm-3d", "vector-tiles-gl",          0],
  ["gl-fdm-3d", "visible-human-explore",    1],
  ["gl-fdm-3d", "visible-human-vtk",        1],
  ["gl-fdm-3d", "visible-human-slicer",     0],
  ["gl-fdm-3d", "visible-human-volume",     4],
  ["gl-fdm-3d", "scivis-primer",            1],
  ["gl-fdm-3d", "shape-from-shading",       0],
  ["gl-fdm-3d", "mol-renderer",             0],
  ["gl-fdm-3d", "conformer-viewer",         0],
  ["gl-fdm-3d", "spectral-color",           0],
  ["gl-fdm-3d", "qft-viz",                  0],
  ["gl-fdm-3d", "backprop",                 0],
  ["gl-fdm-3d", "gpu-patterns",             4],
  ["gl-fdm-3d", "tinyvm",                   0],
  ["gl-fdm-3d", "tinyos",                   0],
  ["gl-fdm-3d", "universal-turing-machine", 0],
  ["gl-fdm-3d", "kanbun-lang",              0],
  ["gl-fdm-3d", "plato",                    0],
  ["gl-fdm-3d", "tidal-sphere",             0],
  ["gl-fdm-3d", "macrobook",                0],
  ["gl-fdm-3d", "telescope",                0],
  ["gl-fdm-3d", "wormhole",                 0],

  // wasm-particle-sim
  ["wasm-particle-sim", "wasm-fvm-cfd",             0],
  ["wasm-particle-sim", "hillshade",                0],
  ["wasm-particle-sim", "shortcut-to-graphics",     0],
  ["wasm-particle-sim", "terrain-faulting",         0],
  ["wasm-particle-sim", "oblique-mercator",         0],
  ["wasm-particle-sim", "raster-tile-renderer",     0],
  ["wasm-particle-sim", "vector-tiles-gl",          0],
  ["wasm-particle-sim", "visible-human-explore",    0],
  ["wasm-particle-sim", "visible-human-vtk",        0],
  ["wasm-particle-sim", "visible-human-slicer",     0],
  ["wasm-particle-sim", "visible-human-volume",     0],
  ["wasm-particle-sim", "scivis-primer",            0],
  ["wasm-particle-sim", "shape-from-shading",       0],
  ["wasm-particle-sim", "mol-renderer",             0],
  ["wasm-particle-sim", "conformer-viewer",         0],
  ["wasm-particle-sim", "spectral-color",           0],
  ["wasm-particle-sim", "qft-viz",                  0],
  ["wasm-particle-sim", "backprop",                 0],
  ["wasm-particle-sim", "gpu-patterns",             0],
  ["wasm-particle-sim", "tinyvm",                   0],
  ["wasm-particle-sim", "tinyos",                   0],
  ["wasm-particle-sim", "universal-turing-machine", 0],
  ["wasm-particle-sim", "kanbun-lang",              0],
  ["wasm-particle-sim", "plato",                    0],
  ["wasm-particle-sim", "tidal-sphere",             4],
  ["wasm-particle-sim", "macrobook",                0],
  ["wasm-particle-sim", "telescope",                0],
  ["wasm-particle-sim", "wormhole",                 0],

  // wasm-fvm-cfd
  ["wasm-fvm-cfd", "hillshade",                0],
  ["wasm-fvm-cfd", "shortcut-to-graphics",     0],
  ["wasm-fvm-cfd", "terrain-faulting",         0],
  ["wasm-fvm-cfd", "oblique-mercator",         0],
  ["wasm-fvm-cfd", "raster-tile-renderer",     0],
  ["wasm-fvm-cfd", "vector-tiles-gl",          0],
  ["wasm-fvm-cfd", "visible-human-explore",    0],
  ["wasm-fvm-cfd", "visible-human-vtk",        0],
  ["wasm-fvm-cfd", "visible-human-slicer",     0],
  ["wasm-fvm-cfd", "visible-human-volume",     0],
  ["wasm-fvm-cfd", "scivis-primer",            0],
  ["wasm-fvm-cfd", "shape-from-shading",       1],
  ["wasm-fvm-cfd", "mol-renderer",             0],
  ["wasm-fvm-cfd", "conformer-viewer",         0],
  ["wasm-fvm-cfd", "spectral-color",           0],
  ["wasm-fvm-cfd", "qft-viz",                  0],
  ["wasm-fvm-cfd", "backprop",                 0],
  ["wasm-fvm-cfd", "gpu-patterns",             0],
  ["wasm-fvm-cfd", "tinyvm",                   0],
  ["wasm-fvm-cfd", "tinyos",                   0],
  ["wasm-fvm-cfd", "universal-turing-machine", 0],
  ["wasm-fvm-cfd", "kanbun-lang",              0],
  ["wasm-fvm-cfd", "plato",                    0],
  ["wasm-fvm-cfd", "tidal-sphere",             0],
  ["wasm-fvm-cfd", "macrobook",                0],
  ["wasm-fvm-cfd", "telescope",                0],
  ["wasm-fvm-cfd", "wormhole",                 0],

  // hillshade
  ["hillshade", "shortcut-to-graphics",     5],
  ["hillshade", "terrain-faulting",         0],
  ["hillshade", "oblique-mercator",         0],
  ["hillshade", "raster-tile-renderer",     0],
  ["hillshade", "vector-tiles-gl",          0],
  ["hillshade", "visible-human-explore",    0],
  ["hillshade", "visible-human-vtk",        0],
  ["hillshade", "visible-human-slicer",     0],
  ["hillshade", "visible-human-volume",     0],
  ["hillshade", "scivis-primer",            0],
  ["hillshade", "shape-from-shading",       4],
  ["hillshade", "mol-renderer",             0],
  ["hillshade", "conformer-viewer",         0],
  ["hillshade", "spectral-color",           0],
  ["hillshade", "qft-viz",                  0],
  ["hillshade", "backprop",                 0],
  ["hillshade", "gpu-patterns",             0],
  ["hillshade", "tinyvm",                   0],
  ["hillshade", "tinyos",                   0],
  ["hillshade", "universal-turing-machine", 0],
  ["hillshade", "kanbun-lang",              1],
  ["hillshade", "plato",                    0],
  ["hillshade", "tidal-sphere",             0],
  ["hillshade", "macrobook",                0],
  ["hillshade", "telescope",                0],
  ["hillshade", "wormhole",                 0],

  // shortcut-to-graphics
  ["shortcut-to-graphics", "terrain-faulting",         0],
  ["shortcut-to-graphics", "oblique-mercator",         0],
  ["shortcut-to-graphics", "raster-tile-renderer",     0],
  ["shortcut-to-graphics", "vector-tiles-gl",          0],
  ["shortcut-to-graphics", "visible-human-explore",    0],
  ["shortcut-to-graphics", "visible-human-vtk",        0],
  ["shortcut-to-graphics", "visible-human-slicer",     0],
  ["shortcut-to-graphics", "visible-human-volume",     0],
  ["shortcut-to-graphics", "scivis-primer",            0],
  ["shortcut-to-graphics", "shape-from-shading",       5],
  ["shortcut-to-graphics", "mol-renderer",             0],
  ["shortcut-to-graphics", "conformer-viewer",         0],
  ["shortcut-to-graphics", "spectral-color",           0],
  ["shortcut-to-graphics", "qft-viz",                  0],
  ["shortcut-to-graphics", "backprop",                 0],
  ["shortcut-to-graphics", "gpu-patterns",             1],
  ["shortcut-to-graphics", "tinyvm",                   0],
  ["shortcut-to-graphics", "tinyos",                   0],
  ["shortcut-to-graphics", "universal-turing-machine", 0],
  ["shortcut-to-graphics", "kanbun-lang",              0],
  ["shortcut-to-graphics", "plato",                    0],
  ["shortcut-to-graphics", "tidal-sphere",             0],
  ["shortcut-to-graphics", "macrobook",                0],
  ["shortcut-to-graphics", "telescope",                0],
  ["shortcut-to-graphics", "wormhole",                 0],

  // terrain-faulting
  ["terrain-faulting", "oblique-mercator",         0],
  ["terrain-faulting", "raster-tile-renderer",     0],
  ["terrain-faulting", "vector-tiles-gl",          0],
  ["terrain-faulting", "visible-human-explore",    0],
  ["terrain-faulting", "visible-human-vtk",        0],
  ["terrain-faulting", "visible-human-slicer",     0],
  ["terrain-faulting", "visible-human-volume",     0],
  ["terrain-faulting", "scivis-primer",            0],
  ["terrain-faulting", "shape-from-shading",       0],
  ["terrain-faulting", "mol-renderer",             0],
  ["terrain-faulting", "conformer-viewer",         0],
  ["terrain-faulting", "spectral-color",           0],
  ["terrain-faulting", "qft-viz",                  0],
  ["terrain-faulting", "backprop",                 0],
  ["terrain-faulting", "gpu-patterns",             0],
  ["terrain-faulting", "tinyvm",                   0],
  ["terrain-faulting", "tinyos",                   0],
  ["terrain-faulting", "universal-turing-machine", 0],
  ["terrain-faulting", "kanbun-lang",              0],
  ["terrain-faulting", "plato",                    0],
  ["terrain-faulting", "tidal-sphere",             1],
  ["terrain-faulting", "macrobook",                0],
  ["terrain-faulting", "telescope",                0],
  ["terrain-faulting", "wormhole",                 0],

  // oblique-mercator
  ["oblique-mercator", "raster-tile-renderer",     0],
  ["oblique-mercator", "vector-tiles-gl",          0],
  ["oblique-mercator", "visible-human-explore",    1],
  ["oblique-mercator", "visible-human-vtk",        1],
  ["oblique-mercator", "visible-human-slicer",     0],
  ["oblique-mercator", "visible-human-volume",     4],
  ["oblique-mercator", "scivis-primer",            1],
  ["oblique-mercator", "shape-from-shading",       0],
  ["oblique-mercator", "mol-renderer",             0],
  ["oblique-mercator", "conformer-viewer",         0],
  ["oblique-mercator", "spectral-color",           0],
  ["oblique-mercator", "qft-viz",                  0],
  ["oblique-mercator", "backprop",                 0],
  ["oblique-mercator", "gpu-patterns",             1],
  ["oblique-mercator", "tinyvm",                   0],
  ["oblique-mercator", "tinyos",                   0],
  ["oblique-mercator", "universal-turing-machine", 0],
  ["oblique-mercator", "kanbun-lang",              0],
  ["oblique-mercator", "plato",                    0],
  ["oblique-mercator", "tidal-sphere",             0],
  ["oblique-mercator", "macrobook",                0],
  ["oblique-mercator", "telescope",                0],
  ["oblique-mercator", "wormhole",                 0],

  // raster-tile-renderer
  ["raster-tile-renderer", "vector-tiles-gl",          4],
  ["raster-tile-renderer", "visible-human-explore",    0],
  ["raster-tile-renderer", "visible-human-vtk",        0],
  ["raster-tile-renderer", "visible-human-slicer",     0],
  ["raster-tile-renderer", "visible-human-volume",     0],
  ["raster-tile-renderer", "scivis-primer",            0],
  ["raster-tile-renderer", "shape-from-shading",       0],
  ["raster-tile-renderer", "mol-renderer",             0],
  ["raster-tile-renderer", "conformer-viewer",         0],
  ["raster-tile-renderer", "spectral-color",           0],
  ["raster-tile-renderer", "qft-viz",                  0],
  ["raster-tile-renderer", "backprop",                 0],
  ["raster-tile-renderer", "gpu-patterns",             0],
  ["raster-tile-renderer", "tinyvm",                   0],
  ["raster-tile-renderer", "tinyos",                   0],
  ["raster-tile-renderer", "universal-turing-machine", 0],
  ["raster-tile-renderer", "kanbun-lang",              0],
  ["raster-tile-renderer", "plato",                    0],
  ["raster-tile-renderer", "tidal-sphere",             0],
  ["raster-tile-renderer", "macrobook",                0],
  ["raster-tile-renderer", "telescope",                0],
  ["raster-tile-renderer", "wormhole",                 0],

  // vector-tiles-gl
  ["vector-tiles-gl", "visible-human-explore",    0],
  ["vector-tiles-gl", "visible-human-vtk",        0],
  ["vector-tiles-gl", "visible-human-slicer",     0],
  ["vector-tiles-gl", "visible-human-volume",     0],
  ["vector-tiles-gl", "scivis-primer",            0],
  ["vector-tiles-gl", "shape-from-shading",       0],
  ["vector-tiles-gl", "mol-renderer",             0],
  ["vector-tiles-gl", "conformer-viewer",         0],
  ["vector-tiles-gl", "spectral-color",           0],
  ["vector-tiles-gl", "qft-viz",                  0],
  ["vector-tiles-gl", "backprop",                 0],
  ["vector-tiles-gl", "gpu-patterns",             0],
  ["vector-tiles-gl", "tinyvm",                   0],
  ["vector-tiles-gl", "tinyos",                   0],
  ["vector-tiles-gl", "universal-turing-machine", 0],
  ["vector-tiles-gl", "kanbun-lang",              0],
  ["vector-tiles-gl", "plato",                    0],
  ["vector-tiles-gl", "tidal-sphere",             0],
  ["vector-tiles-gl", "macrobook",                0],
  ["vector-tiles-gl", "telescope",                0],
  ["vector-tiles-gl", "wormhole",                 0],

  // visible-human-explore
  ["visible-human-explore", "visible-human-vtk",        5],
  ["visible-human-explore", "visible-human-slicer",     5],
  ["visible-human-explore", "visible-human-volume",     5],
  ["visible-human-explore", "scivis-primer",            4],
  ["visible-human-explore", "shape-from-shading",       0],
  ["visible-human-explore", "mol-renderer",             0],
  ["visible-human-explore", "conformer-viewer",         0],
  ["visible-human-explore", "spectral-color",           2],
  ["visible-human-explore", "qft-viz",                  0],
  ["visible-human-explore", "backprop",                 1],
  ["visible-human-explore", "gpu-patterns",             0],
  ["visible-human-explore", "tinyvm",                   0],
  ["visible-human-explore", "tinyos",                   0],
  ["visible-human-explore", "universal-turing-machine", 0],
  ["visible-human-explore", "kanbun-lang",              0],
  ["visible-human-explore", "plato",                    0],
  ["visible-human-explore", "tidal-sphere",             0],
  ["visible-human-explore", "macrobook",                0],
  ["visible-human-explore", "telescope",                0],
  ["visible-human-explore", "wormhole",                 0],

  // visible-human-vtk
  ["visible-human-vtk", "visible-human-slicer",     5],
  ["visible-human-vtk", "visible-human-volume",     5],
  ["visible-human-vtk", "scivis-primer",            4],
  ["visible-human-vtk", "shape-from-shading",       0],
  ["visible-human-vtk", "mol-renderer",             0],
  ["visible-human-vtk", "conformer-viewer",         0],
  ["visible-human-vtk", "spectral-color",           2],
  ["visible-human-vtk", "qft-viz",                  0],
  ["visible-human-vtk", "backprop",                 0],
  ["visible-human-vtk", "gpu-patterns",             0],
  ["visible-human-vtk", "tinyvm",                   0],
  ["visible-human-vtk", "tinyos",                   0],
  ["visible-human-vtk", "universal-turing-machine", 0],
  ["visible-human-vtk", "kanbun-lang",              0],
  ["visible-human-vtk", "plato",                    0],
  ["visible-human-vtk", "tidal-sphere",             0],
  ["visible-human-vtk", "macrobook",                0],
  ["visible-human-vtk", "telescope",                0],
  ["visible-human-vtk", "wormhole",                 0],

  // visible-human-slicer
  ["visible-human-slicer", "visible-human-volume",     4],
  ["visible-human-slicer", "scivis-primer",            0],
  ["visible-human-slicer", "shape-from-shading",       0],
  ["visible-human-slicer", "mol-renderer",             0],
  ["visible-human-slicer", "conformer-viewer",         0],
  ["visible-human-slicer", "spectral-color",           1],
  ["visible-human-slicer", "qft-viz",                  0],
  ["visible-human-slicer", "backprop",                 0],
  ["visible-human-slicer", "gpu-patterns",             0],
  ["visible-human-slicer", "tinyvm",                   0],
  ["visible-human-slicer", "tinyos",                   0],
  ["visible-human-slicer", "universal-turing-machine", 0],
  ["visible-human-slicer", "kanbun-lang",              0],
  ["visible-human-slicer", "plato",                    0],
  ["visible-human-slicer", "tidal-sphere",             0],
  ["visible-human-slicer", "macrobook",                0],
  ["visible-human-slicer", "telescope",                0],
  ["visible-human-slicer", "wormhole",                 0],

  // visible-human-volume
  ["visible-human-volume", "scivis-primer",            4],
  ["visible-human-volume", "shape-from-shading",       0],
  ["visible-human-volume", "mol-renderer",             0],
  ["visible-human-volume", "conformer-viewer",         0],
  ["visible-human-volume", "spectral-color",           0],
  ["visible-human-volume", "qft-viz",                  0],
  ["visible-human-volume", "backprop",                 0],
  ["visible-human-volume", "gpu-patterns",             0],
  ["visible-human-volume", "tinyvm",                   0],
  ["visible-human-volume", "tinyos",                   0],
  ["visible-human-volume", "universal-turing-machine", 0],
  ["visible-human-volume", "kanbun-lang",              0],
  ["visible-human-volume", "plato",                    0],
  ["visible-human-volume", "tidal-sphere",             0],
  ["visible-human-volume", "macrobook",                0],
  ["visible-human-volume", "telescope",                0],
  ["visible-human-volume", "wormhole",                 0],

  // scivis-primer
  ["scivis-primer", "shape-from-shading",       0],
  ["scivis-primer", "mol-renderer",             0],
  ["scivis-primer", "conformer-viewer",         0],
  ["scivis-primer", "spectral-color",           0],
  ["scivis-primer", "qft-viz",                  0],
  ["scivis-primer", "backprop",                 0],
  ["scivis-primer", "gpu-patterns",             0],
  ["scivis-primer", "tinyvm",                   0],
  ["scivis-primer", "tinyos",                   0],
  ["scivis-primer", "universal-turing-machine", 0],
  ["scivis-primer", "kanbun-lang",              0],
  ["scivis-primer", "plato",                    0],
  ["scivis-primer", "tidal-sphere",             0],
  ["scivis-primer", "macrobook",                0],
  ["scivis-primer", "telescope",                0],
  ["scivis-primer", "wormhole",                 0],

  // shape-from-shading
  ["shape-from-shading", "mol-renderer",             0],
  ["shape-from-shading", "conformer-viewer",         0],
  ["shape-from-shading", "spectral-color",           1],
  ["shape-from-shading", "qft-viz",                  2],
  ["shape-from-shading", "backprop",                 0],
  ["shape-from-shading", "gpu-patterns",             0],
  ["shape-from-shading", "tinyvm",                   0],
  ["shape-from-shading", "tinyos",                   0],
  ["shape-from-shading", "universal-turing-machine", 0],
  ["shape-from-shading", "kanbun-lang",              0],
  ["shape-from-shading", "plato",                    0],
  ["shape-from-shading", "tidal-sphere",             0],
  ["shape-from-shading", "macrobook",                0],
  ["shape-from-shading", "telescope",                0],
  ["shape-from-shading", "wormhole",                 0],

  // mol-renderer
  ["mol-renderer", "conformer-viewer",         5],
  ["mol-renderer", "spectral-color",           0],
  ["mol-renderer", "qft-viz",                  0],
  ["mol-renderer", "backprop",                 0],
  ["mol-renderer", "gpu-patterns",             0],
  ["mol-renderer", "tinyvm",                   0],
  ["mol-renderer", "tinyos",                   0],
  ["mol-renderer", "universal-turing-machine", 0],
  ["mol-renderer", "kanbun-lang",              0],
  ["mol-renderer", "plato",                    0],
  ["mol-renderer", "tidal-sphere",             1],
  ["mol-renderer", "macrobook",                0],
  ["mol-renderer", "telescope",                0],
  ["mol-renderer", "wormhole",                 0],

  // conformer-viewer
  ["conformer-viewer", "spectral-color",           0],
  ["conformer-viewer", "qft-viz",                  0],
  ["conformer-viewer", "backprop",                 0],
  ["conformer-viewer", "gpu-patterns",             0],
  ["conformer-viewer", "tinyvm",                   0],
  ["conformer-viewer", "tinyos",                   0],
  ["conformer-viewer", "universal-turing-machine", 0],
  ["conformer-viewer", "kanbun-lang",              0],
  ["conformer-viewer", "plato",                    0],
  ["conformer-viewer", "tidal-sphere",             1],
  ["conformer-viewer", "macrobook",                0],
  ["conformer-viewer", "telescope",                0],
  ["conformer-viewer", "wormhole",                 0],

  // spectral-color
  ["spectral-color", "qft-viz",                  0],
  ["spectral-color", "backprop",                 1],
  ["spectral-color", "gpu-patterns",             0],
  ["spectral-color", "tinyvm",                   0],
  ["spectral-color", "tinyos",                   0],
  ["spectral-color", "universal-turing-machine", 0],
  ["spectral-color", "kanbun-lang",              0],
  ["spectral-color", "plato",                    0],
  ["spectral-color", "tidal-sphere",             0],
  ["spectral-color", "macrobook",                0],
  ["spectral-color", "telescope",                0],
  ["spectral-color", "wormhole",                 0],

  // qft-viz
  ["qft-viz", "backprop",                 1],
  ["qft-viz", "gpu-patterns",             0],
  ["qft-viz", "tinyvm",                   0],
  ["qft-viz", "tinyos",                   0],
  ["qft-viz", "universal-turing-machine", 1],
  ["qft-viz", "kanbun-lang",              0],
  ["qft-viz", "plato",                    0],
  ["qft-viz", "tidal-sphere",             0],
  ["qft-viz", "macrobook",                0],
  ["qft-viz", "telescope",                0],
  ["qft-viz", "wormhole",                 0],

  // backprop
  ["backprop", "gpu-patterns",             0],
  ["backprop", "tinyvm",                   0],
  ["backprop", "tinyos",                   0],
  ["backprop", "universal-turing-machine", 1],
  ["backprop", "kanbun-lang",              0],
  ["backprop", "plato",                    2],
  ["backprop", "tidal-sphere",             0],
  ["backprop", "macrobook",                0],
  ["backprop", "telescope",                0],
  ["backprop", "wormhole",                 0],

  // gpu-patterns
  ["gpu-patterns", "tinyvm",                   0],
  ["gpu-patterns", "tinyos",                   0],
  ["gpu-patterns", "universal-turing-machine", 0],
  ["gpu-patterns", "kanbun-lang",              0],
  ["gpu-patterns", "plato",                    0],
  ["gpu-patterns", "tidal-sphere",             0],
  ["gpu-patterns", "macrobook",                0],
  ["gpu-patterns", "telescope",                0],
  ["gpu-patterns", "wormhole",                 0],

  // tinyvm
  ["tinyvm", "tinyos",                   5],
  ["tinyvm", "universal-turing-machine", 3],
  ["tinyvm", "kanbun-lang",              1],
  ["tinyvm", "plato",                    0],
  ["tinyvm", "tidal-sphere",             0],
  ["tinyvm", "macrobook",                3],
  ["tinyvm", "telescope",                0],
  ["tinyvm", "wormhole",                 0],

  // tinyos
  ["tinyos", "universal-turing-machine", 0],
  ["tinyos", "kanbun-lang",              0],
  ["tinyos", "plato",                    0],
  ["tinyos", "tidal-sphere",             0],
  ["tinyos", "macrobook",                0],
  ["tinyos", "telescope",                3],
  ["tinyos", "wormhole",                 3],

  // universal-turing-machine
  ["universal-turing-machine", "kanbun-lang",              0],
  ["universal-turing-machine", "plato",                    0],
  ["universal-turing-machine", "tidal-sphere",             0],
  ["universal-turing-machine", "macrobook",                3],
  ["universal-turing-machine", "telescope",                0],
  ["universal-turing-machine", "wormhole",                 0],

  // kanbun-lang
  ["kanbun-lang", "plato",                    0],
  ["kanbun-lang", "tidal-sphere",             0],
  ["kanbun-lang", "macrobook",                0],
  ["kanbun-lang", "telescope",                0],
  ["kanbun-lang", "wormhole",                 0],

  // plato
  ["plato", "tidal-sphere",             0],
  ["plato", "macrobook",                0],
  ["plato", "telescope",                0],
  ["plato", "wormhole",                 0],

  // tidal-sphere
  ["tidal-sphere", "macrobook",                0],
  ["tidal-sphere", "telescope",                0],
  ["tidal-sphere", "wormhole",                 0],

  // macrobook
  ["macrobook", "telescope",                0],
  ["macrobook", "wormhole",                 0],

  // telescope
  ["telescope", "wormhole",                 5],
];